--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Rover17-Dev/PlayerReport
build-by-default: true
branches:
- main
projects:
  PlayerReport:
    path: ""
    libs:
    - src: dresnite/EasyUI/libEasyUI
      version: ^1.0.3
      branch: pm5
    - src: ialdrich23xx\libasynwebhook
      version: ^1.1.0
...
